name: Deploy Docs

on:
  push:
    branches:
      - main  # Запускать workflow при пуше в ветку main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Получить код из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установить Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Указать версию Python

      # Шаг 3: Установить зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Шаг 4: Создать директории, если они отсутствуют
      - name: Create directories if they don't exist
        run: |
          mkdir -p src script

      # Шаг 5: Запустить Flake8 (линтер)
      - name: Run Flake8 (Linting)
        run: |
          if [ -d "src/" ]; then
            flake8 src/ --max-line-length=88 --show-source --statistics
          fi
          if [ -d "script/" ]; then
            flake8 script/ --max-line-length=88 --show-source --statistics
          fi

      # Шаг 6: Запустить Black (форматтер)
      - name: Run Black (Code Formatting)
        run: |
          if [ -d "src/" ]; then
            black src/ --check
          fi
          if [ -d "script/" ]; then
            black script/ --check
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: lint-and-format  # Зависит от успешного выполнения линтинга и форматирования
    steps:
      # Шаг 1: Получить код из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установить Quarto
      - name: Install Quarto
        run: |
          curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb
          sudo dpkg -i quarto-linux-amd64.deb
          quarto check

      # Шаг 3: Установить зависимости Python
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Шаг 4: Конвертировать Jupyter Notebook в Quarto
      - name: Convert Jupyter notebooks to Quarto
        run: sh script/convert-jupyter-quarto.sh

      # Шаг 5: Опубликовать документацию
      - name: Deploy docs
        run: |
          quarto publish gh-pages